DriveApp/Drive/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path("", views.index, name="home_page"),
    path("files", views.files, name="files_page"),
    path("files/<slug:slug>",views.file_details, name="file_details"),
    path('file-upload', views.file_upload, name='file_upload'),
    path('file-dowload/<slug:file_slug>/', views.download_file, name='download_file'),
    path('user-files', views.user_files, name='user_files'),
    path('edit-file/<slug:file_slug>/', views.edit_file, name='edit_file'),
    path('scholls', views.scholl_list, name='scholl_list'),
    path('add-school', views.add_school, name='add_school'),
    path('departments/', views.department_list, name='department_list'),
    path('add-department', views.add_department, name='add_department'),
    path('add-lesson', views.add_lesson, name='add_lesson'),
    path('lessons/', views.lesson_list, name='lesson_list'),
    path('add-outhor', views.add_outhor, name='add_outhor'),
    path('outhors/', views.outhor_list, name='outhor_list'),
    path('profile-list/', views.profile_list, name='profile_list'),
    path('404/', TemplateView.as_view(template_name='Drive/404-Message.html'), name='404'),
]

DriveApp/DriveApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include("Landing.urls")),
    path('OCRApp/',include("OCRApp.urls")),
    path('Drive/',include("Drive.urls")),
    path('Account/',include("Account.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

DriveApp/Drive/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core import validators
from django.core.validators import MaxLengthValidator,MinLengthValidator
from django.db.models.fields import CharField
from ckeditor.fields import RichTextField
from django.core.validators import MinLengthValidator, MaxLengthValidator
import uuid


class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    adress = models.CharField("Adres", max_length=400)
    email = models.EmailField("E-Posta", null=True, blank=True)
    phone1 = models.CharField("Telefon 1", max_length=20,null=True, blank=True)
    phone2 = models.CharField("Telefon 2", max_length=20,null=True, blank=True)

    class Meta:
        verbose_name = "İletişim"
        verbose_name_plural = "İletişimler"

    def __str__(self):
        return self.email

class Scholl(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Okul(Üniversite) Adı", max_length=100)
    description = models.TextField("Açıklama",max_length=5000, null=True, blank=True)
    banner = models.ImageField("Bölüm Logosu", upload_to="Drive",null=True, blank=True)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = "Okul"
        verbose_name_plural = "Okullar"
    
    def __str__(self):
        return self.name
    
class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Bölüm(Departman) Adı", max_length=100)
    description = models.TextField("Açıklama",max_length=5000, null=True, blank=True)
    banner = models.ImageField("Bölüm Logosu", upload_to="Drive",null=True, blank=True)
    scholl = models.ManyToManyField(Scholl)

    class Meta:
        verbose_name = "Bölüm"
        verbose_name_plural = "Bölümler"
    
    def __str__(self):
        return self.name

class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Ders Adı", max_length=100)
    description = models.TextField("Açıklama",max_length=5000, null=True, blank=True)
    department = models.ManyToManyField(Department)

    class Meta:
        verbose_name = "Ders"
        verbose_name_plural = "Dersler"

    def __str__(self):
        return self.name

class Outhor(models.Model):
    genders = (
        ('M', 'Erkek'),
        ('F', 'Kadin'),
    )

    title_tpyes = (
        ('1','Profesör'),
        ('2','Doçent'),
        ('3','Doktor'),
        ('4','Öğretim Görevlisi'),
        ('5','Araştirma Görevlisi'),
        ('6','Öğretmen'),
        ('7','Yazar'),
        ('8','Araştirmaci'),
        ('9','Üye'),
    )

    id = models.AutoField(primary_key=True)
    first_name = models.CharField("Adı", max_length=100)
    last_name = models.CharField("Soyadı", max_length=100)
    biography = models.TextField("Özgeçmiş", max_length=3000, null=True, blank=True)
    image_name = models.ImageField("Profil Resmi", upload_to="Drive",null=True, blank=True)
    date_of_birth = models.DateField("Doğum Tarihi", null=True, blank=True)
    gender = models.CharField("Cinsiyet", max_length=1, choices=genders)
    title_type = models.CharField("Ünvan", max_length=1, choices=title_tpyes)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE, null=True, blank=True)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}" 
    
    full_name.fget.short_description = "Ad Soyad"

    class Meta:
        verbose_name = "Yazar"
        verbose_name_plural = "Yazarlar"

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.title_tpyes[int(self.title_type)-1][1]})"
  
class File(models.Model):
    languages = (
        ('Türkçe','Türkçe'),
        ('İngilizce','İngilizce'),
        ('Fransızca','Fransızca'),
        ('Almanca','Almanca'),
        ('İtalyanca','İtalyanca'),
    )

    id = models.AutoField(primary_key=True)
    title = models.CharField("Dosya Başlığı", max_length=250,null=True, blank=True)
    description = models.TextField("Açıklama", null=True, blank=True)
    file_name = models.FileField("Dosya", upload_to="Drive",null=True, blank=True)
    file_cover = models.ImageField("Dosya Resmi", upload_to="Drive",null=True, blank=True)
    upload_date = models.DateTimeField(auto_now=True)
    date = models.DateField("Yüklenme Tarihi", null=True, blank=True)
    slug = models.SlugField(unique=True,db_index=True)
    language = models.CharField("Dil", max_length=100, choices=languages)
    outhor = models.ForeignKey(Outhor,on_delete=models.SET_NULL, null=True,blank=True)
    scholl = models.ForeignKey(Scholl, models.SET_NULL, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=0)
    is_home = models.BooleanField(default=0)

    class Meta:
        verbose_name = "Dosya"
        verbose_name_plural = "Dosyalar"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = str(uuid.uuid4())[:8]

        super().save(*args, **kwargs)

class Slider(models.Model):
        id = models.AutoField(primary_key=True)
        title = models.CharField(max_length=200)
        image = models.ImageField(upload_to="files")
        file = models.ForeignKey(File, on_delete=models.SET_NULL, null=True, blank=True)
        is_active = models.BooleanField(default=False)

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField("Kullanıcı Adı", max_length=30)
    email = models.EmailField("E-Posta", default="")
    text = models.TextField("Yorum", max_length=500)
    rating = models.IntegerField("Oy", null=True)
    date_added = models.DateTimeField("Yorum Tarihi", auto_now=True, null=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE, related_name="comments")

    class Meta:
        verbose_name = "Yorum"
        verbose_name_plural = "Yorumlar"

DriveApp/Drive/views.py
from datetime import date
from django.shortcuts import render, get_object_or_404, redirect
from Drive.forms import CommentForm, FileUploadForm, FileEditForm, SchollForm, DepartmentForm, LessonForm, OuthorForm
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse
from Drive.models import File, Slider, Scholl, Department, Lesson, Outhor
from Account.models import Profile
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='/Account/login')
def index(request):
    files = File.objects.filter(is_active=True, is_home=True) 
    sliders= Slider.objects.filter(is_active=True)
    return render(request, 'Drive/index.html',{
        "files": files,
        "sliders":sliders
    })

@login_required(login_url='/Account/login')
def files(request):
    files = File.objects.filter(is_active=True) 
    return render(request,'Drive/files.html',{
        "files": files
    })

@login_required(login_url='/Account/login')
def file_details(request, slug):

    file = get_object_or_404(File, slug=slug)
    comment_form = CommentForm()

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.file = file
            comment.save()
            return HttpResponseRedirect(reverse("file_details", args=[slug]))

    return render(request,'Drive/file-details.html',{
        "file": file,
        "comments":file.comments.all().order_by("-date_added"),
        "comment_form": comment_form
    })

@login_required(login_url='/Account/login')
def file_upload(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            file_instance = form.save(commit=False)
            file_instance.date = timezone.now()
            file_instance.user = request.user
            file_instance.save()
            messages.success(request,"Dosya Yüklendi")
            return redirect('file_upload')
        else:
            print(form.errors)
    else:
        form = FileUploadForm()


    return render(request, 'Drive/file-upload.html', {'form': form})

@login_required(login_url='/Account/login')
def download_file(request, file_slug):
    file_obj = get_object_or_404(File, slug=file_slug)
    file_data = file_obj.file_name.read()
    response = HttpResponse(file_data, content_type='application/octet-stream')
    response['Content-Disposition'] = f'attachment; filename="{file_obj.file_name.name}"'

    return response

@login_required(login_url='/Account/login')
def user_files(request):
    user_files = File.objects.filter(user=request.user)
    return render(request, 'Drive/user-files.html',{'user_files':user_files})

@login_required(login_url='/Account/login')
def edit_file(request, file_slug):
    file_instance = get_object_or_404(File, slug=file_slug)
    
    if request.method == 'POST':
        form = FileEditForm(request.POST, instance=file_instance)
        if form.is_valid():
            form.save()
            # Başarılı bir şekilde kaydedildiğinde yapılacak işlemler
    else:
        form = FileEditForm(instance=file_instance)
    
    return render(request, 'Drive/edit-file.html', {'form': form})

@login_required(login_url='/Account/login')
def add_school(request):
    if request.method == 'POST':
        form = SchollForm(request.POST)
        if form.is_valid():
            form.save()
            # Başarılı ekleme mesajı, başka bir sayfaya yönlendirme vs. burada yapılabilir.
    else:
        form = SchollForm()

    return render(request, 'Drive/addForms/add-school.html', {'form': form})

@login_required(login_url='/Account/login')
def scholl_list(request):
    scholls = Scholl.objects.all()
    return render(request, 'Drive/scholl-list.html', {'scholls': scholls})

@login_required(login_url='/Account/login')
def add_department(request):
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            # Başarılı ekleme mesajı, başka bir sayfaya yönlendirme vs. burada yapılabilir.
    else:
        form = DepartmentForm()

    return render(request, 'Drive/addForms/add-department.html', {'form': form})

def department_list(request):
    departments = Department.objects.all()
    return render(request, 'Drive/department-list.html', {'departments': departments})

@login_required(login_url='/Account/login')
def add_lesson(request):
    if request.method == 'POST':
        form = LessonForm(request.POST)
        if form.is_valid():
            form.save()
            # Başarılı ekleme mesajı, başka bir sayfaya yönlendirme vs. burada yapılabilir.
    else:
        form = LessonForm()
    return render(request, 'Drive/addForms/add-lesson.html', {'form': form})

@login_required(login_url='/Account/login')
def lesson_list(request):
    lessons = Lesson.objects.all()
    return render(request, 'Drive/lesson-list.html', {'lessons': lessons})

@login_required(login_url='/Account/login')
def add_outhor(request):
    if request.method=='POST':
        form = OuthorForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = OuthorForm()
    return render(request, 'Drive/addForms/add-outhor.html',{'form':form})

@login_required(login_url='/Account/login')
def outhor_list(request):
    outhors = Outhor.objects.all()
    return render(request, 'Drive/outhor-list.html', {'outhors': outhors})

@login_required(login_url='/Account/login')
def profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'Drive/profile-list.html', {'profiles': profiles})

DriveApp/Drive/templates/Drive/404-Message.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Index {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                
                <div class="container-fluid">

                    <div class="container-fluid">
                        <div class="text-center">
                           <div class="error mx-auto" data-text="404">404</div>
                           <p class="lead text-gray-800 mb-5">Sayfa Bulunamadı</p>
                           <p class="text-gray-500 mb-0">Görünüşe göre Matrixde bir hata buldun ;)</p>
                           <a href="{% url "home_page" %}">← Anasayfaya Dön</a>
                        </div>
                     </div>


                    </div>
                </div>
            </div>

        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}

DriveApp/Drive/templates/Drive/department-list.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Index {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                
                <div class="container-fluid">
                    <div class="d-sm-flex align-items-center justify-content-between mt-4 mb-3">
                       <h1 class="h5 mb-0 text-gray-900">Departman(Bölüm) Listesi</h1>
                       <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Reset Filters <i class="fas fa-times fa-sm text-white-50"></i></a>
                    </div>
                    <div class="row">

                       <div class="col-xl-9 col-lg-8">
                          <div class="row">
                            {% for department  in departments   %}
                             <div class="col-xl-4 col-md-6 mb-4">
                                <div class="card e-card shadow border-0">
                                   <a href="{% url "404" %}">
                                        <div class="m-card-cover">
                                            {% if department.banner %}
                                                <img src="{{ department.banner.url }}" alt="{{ department.name }} Banner">
                                            {% endif %}
                                        </div>
                                      <div class="card-body p-0">
                                         <div class="row no-gutters align-items-center">
                                            <div class="col-10 p-3">
                                               <p class="card-text text-gray-900 mb-1">{{ department.name }}</p>
                                            </div>
                                         </div>
                                      </div>
                                   </a>
                                </div>
                             </div>
                             {% endfor %}
                          </div>

                       </div>
                    </div>
                 </div>
                
                
            </div>

            {% include "partials/_footer.html" %}
        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}

DriveApp/Drive/templates/Drive/edit-file.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Dosya Düzenleme Sayfası {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                <div class="container-fluid" >

                    <div class="row">

                        <div class="col-xl-9 col-lg-9">
                            <div class="bg-white p-3 widget shadow rounded mb-4">
                                <div id="sidebar-1-1">
                                    <div class=" d-sm-flex align-items-center justify-content-between mb-3">
                                        <h1 class="h5 mb-0 text-gray-900">Dosya Düzenle</h1>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col">
                                            <form method="post" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                {{ form.file_cover.errors }}
                                                {% for field in form %}
                                                    {% if field.name != 'file_cover' %}
                                                        <div class="form-group">
                                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                                            {{ field }}
                                                        </div>
                                                    {% endif %}
                                                {% endfor %}
                                                <button type="submit" class="btn btn-primary">Yükle</button>
                                            </form>
                                            </form>
                                        </div>
                                    </div>
                                    </div>
                            </div>
                          </div>
                    </div>
                </div>              
            </div>

            <script>
                document.querySelectorAll("#sidebar-1 .nav-link")[0].classList.add("active")
            </script>

            {% include "partials/_footer.html" %}
        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}

DriveApp/Drive/templates/Drive/file-upload.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Dosya Yükleme Sayfası {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                <div class="container-fluid" >

                    <div class="row">
                        <div class="col-xl-3 col-lg-3">
                            {% include "partials/_add-menu.html" %}
                        </div>
                        <div class="col-xl-9 col-lg-9">
                            <div class="bg-white p-3 widget shadow rounded mb-4">
                                <div id="sidebar-1-1">
                                    <div class=" d-sm-flex align-items-center justify-content-between mb-3">
                                        <h1 class="h5 mb-0 text-gray-900">Dosya Yükle</h1>
                                    </div>
                                    
                                    <div class="row">
                                        <div class="col">
                                            <form method="POST" enctype="multipart/form-data">
                                                {% csrf_token %}
                                                {{ form.file_cover.errors }}
                                                {% for field in form %}
                                                    {% if field.name != 'file_cover' %}
                                                        <div class="form-group">
                                                            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                                                            {{ field }}
                                                        </div>
                                                    {% endif %}
                                                {% endfor %}
                                                <button type="submit" class="btn btn-primary">Yükle</button>
                                            </form>
                                            </form>
                                        </div>
                                    </div>
                                    </div>
                            </div>
                          </div>
                    </div>
                </div>              
            </div>

            <script>
                document.querySelectorAll("#sidebar-1 .nav-link")[0].classList.add("active")
            </script>

            {% include "partials/_footer.html" %}
        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}

DriveApp/Drive/templates/Drive/outhor-list.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Index {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                
                <div class="container-fluid">
                    <div class="d-sm-flex align-items-center justify-content-between mt-4 mb-3">
                       <h1 class="h5 mb-0 text-gray-900">Yazar Listesi</h1>
                       <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Reset Filters <i class="fas fa-times fa-sm text-white-50"></i></a>
                    </div>
                    <div class="row">
                       <div class="col-xl-12 col-lg-12">
                            <div class="row">
                                {% for outhor in outhors %}
                                    <div class="col-xl-4 col-md-6 mb-4">
                                        <div class="card p-card shadow border-0">
                                            <a href="{% url "404" %}">
                                            <div class="row no-gutters">
                                                <div class="col-md-4">
                                                    <img src="{{ outhor.image_name.url }}" class="card-img" alt="...">
                                                </div>
                                                <div class="col-md-8">
                                                    <div class="card-body">
                                                    <h5 class="card-title text-gray-900">{{ outhor.first_name }} {{ outhor.last_name }}</h5>
                                                    <p class="card-text">{{ outhor.biography|slice:":50" }}</p>
                                                    <p class="card-text"><small><span class="text-muted pr-2"><i class="fas fa-film fa-sm ml-1"></i>{{ outhor.get_title_type_display }}</span> <span class="text-link">İletişim Bilgisi: {{ author.contact }}</span></small></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                        </div>
                                    </div>
                                {% endfor %}
                          </div>
                       </div>
                    </div>
                 </div>

            {% include "partials/_footer.html" %}
        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}

DriveApp/Drive/templates/Drive/profile-list.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Index {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                
                <div class="container-fluid">
                    <div class="d-sm-flex align-items-center justify-content-between mt-4 mb-3">
                       <h1 class="h5 mb-0 text-gray-900">Kullanıcı Listesi</h1>
                       <a href="#" class="d-none d-sm-inline-block btn btn-sm btn-primary shadow-sm">Reset Filters <i class="fas fa-times fa-sm text-white-50"></i></a>
                    </div>
                    <div class="row">
                       <div class="col-xl-12 col-lg-12">
                            <div class="row">
                                {% for profile in profiles %}
                                    <div class="col-xl-4 col-md-6 mb-4">
                                        <div class="card p-card shadow border-0">
                                            <a href="{% url "404" %}">
                                            <div class="row no-gutters">
                                                <div class="col-md-4">
                                                    <img src="{{ profile.avatar}} " class="card-img" alt="..." >
                                                </div>
                                                <div class="col-md-8">
                                                    <div class="card-body">
                                                    <h5 class="card-title text-gray-900">{{ profile.User. }} {{ profile.last_name }}</h5>
                                                    <p class="card-text">{{ profile.biography|slice:":50" }}</p>
                                                    <p class="card-text"><small><span class="text-muted pr-2"><i class="fas fa-film fa-sm ml-1"></i>{{ profile.get_title_type_display }}</span> <span class="text-link">İletişim Bilgisi: {{ author.contact }}</span></small></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                        </div>
                                    </div>
                                {% endfor %}
                          </div>
                       </div>
                    </div>
                 </div>
                 

            {% include "partials/_footer.html" %}
        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}

DriveApp/Drive/templates/Drive/user-files.html
{% extends "Drive/base.html" %} 
{% load static %} 

{% block css_files %} 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick.min.css"%} "/> 
    <link rel="stylesheet" type="text/css" href="{% static "Drive/vendor/slick/slick-theme.min.css" %}" /> 
{% endblock %} 
{% block page_title %} Index {% endblock %} 

{% block content %}
    <div id="wrapper">
        {% include "partials/_sidebar.html" %}
      
        <div id="content-wrapper" class="d-flex flex-column">
            <div id="content">
                
                {% include "partials/_topbar.html" %}
                <div class="container-fluid">
                    <div class="d-sm-flex align-items-center justify-content-between mt-4 mb-3">
                       <h1 class="h5 mb-0 text-gray-900">Dosyalarım</h1>
                    </div>
                    <div class="row">
                     {% for file in user_files  %}
                        <div class="col-xl-3 col-md-4 mb-4">
                           {% include "partials/_user-uploaded-files.html" %}                       
                        </div>
                     {% endfor %}
                    </div>
                 </div>
            </div>

            {% include "partials/_footer.html" %}
        </div>
    </div>
{% endblock %}

{% block js_files %}
{% endblock %}