DriveApp/Drive/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

urlpatterns = [
    path("", views.index, name="home_page"),
    path("files", views.files, name="files_page"),
    path("files/<slug:slug>",views.file_details, name="file_details"),
    path('file-upload', views.file_upload, name='file_upload'),
    path('file-dowload/<slug:file_slug>/', views.download_file, name='download_file'),
    path('user-files', views.user_files, name='user_files'),
    path('edit-file/<slug:file_slug>/', views.edit_file, name='edit_file'),
    path('scholls', views.scholl_list, name='scholl_list'),
    path('add-school', views.add_school, name='add_school'),
    path('departments/', views.department_list, name='department_list'),
    path('add-department', views.add_department, name='add_department'),
    path('add-lesson', views.add_lesson, name='add_lesson'),
    path('lessons/', views.lesson_list, name='lesson_list'),
    path('add-outhor', views.add_outhor, name='add_outhor'),
    path('outhors/', views.outhor_list, name='outhor_list'),
    path('profile-list/', views.profile_list, name='profile_list'),
    path('404/', TemplateView.as_view(template_name='Drive/404-Message.html'), name='404'),
]

DriveApp/DriveApp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('',include("Landing.urls")),
    path('OCRApp/',include("OCRApp.urls")),
    path('Drive/',include("Drive.urls")),
    path('Account/',include("Account.urls")),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
 

DriveApp/Drive/models.py
from django.contrib.auth.models import User
from django.db import models
from django.core import validators
from django.core.validators import MaxLengthValidator,MinLengthValidator
from django.db.models.fields import CharField
from ckeditor.fields import RichTextField
from django.core.validators import MinLengthValidator, MaxLengthValidator
import uuid


class Contact(models.Model):
    id = models.AutoField(primary_key=True)
    adress = models.CharField("Adres", max_length=400)
    email = models.EmailField("E-Posta", null=True, blank=True)
    phone1 = models.CharField("Telefon 1", max_length=20,null=True, blank=True)
    phone2 = models.CharField("Telefon 2", max_length=20,null=True, blank=True)

    class Meta:
        verbose_name = "İletişim"
        verbose_name_plural = "İletişimler"

    def __str__(self):
        return self.email

class Scholl(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Okul(Üniversite) Adı", max_length=100)
    description = models.TextField("Açıklama",max_length=5000, null=True, blank=True)
    banner = models.ImageField("Bölüm Logosu", upload_to="Drive",null=True, blank=True)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE, null=True, blank=True)

    class Meta:
        verbose_name = "Okul"
        verbose_name_plural = "Okullar"
    
    def __str__(self):
        return self.name
    
class Department(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Bölüm(Departman) Adı", max_length=100)
    description = models.TextField("Açıklama",max_length=5000, null=True, blank=True)
    banner = models.ImageField("Bölüm Logosu", upload_to="Drive",null=True, blank=True)
    scholl = models.ManyToManyField(Scholl)

    class Meta:
        verbose_name = "Bölüm"
        verbose_name_plural = "Bölümler"
    
    def __str__(self):
        return self.name

class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField("Ders Adı", max_length=100)
    description = models.TextField("Açıklama",max_length=5000, null=True, blank=True)
    department = models.ManyToManyField(Department)

    class Meta:
        verbose_name = "Ders"
        verbose_name_plural = "Dersler"

    def __str__(self):
        return self.name

class Outhor(models.Model):
    genders = (
        ('M', 'Erkek'),
        ('F', 'Kadin'),
    )

    title_tpyes = (
        ('1','Profesör'),
        ('2','Doçent'),
        ('3','Doktor'),
        ('4','Öğretim Görevlisi'),
        ('5','Araştirma Görevlisi'),
        ('6','Öğretmen'),
        ('7','Yazar'),
        ('8','Araştirmaci'),
        ('9','Üye'),
    )

    id = models.AutoField(primary_key=True)
    first_name = models.CharField("Adı", max_length=100)
    last_name = models.CharField("Soyadı", max_length=100)
    biography = models.TextField("Özgeçmiş", max_length=3000, null=True, blank=True)
    image_name = models.ImageField("Profil Resmi", upload_to="Drive",null=True, blank=True)
    date_of_birth = models.DateField("Doğum Tarihi", null=True, blank=True)
    gender = models.CharField("Cinsiyet", max_length=1, choices=genders)
    title_type = models.CharField("Ünvan", max_length=1, choices=title_tpyes)
    contact = models.OneToOneField(Contact, on_delete=models.CASCADE, null=True, blank=True)

    @property
    def full_name(self):
        return f"{self.first_name} {self.last_name}" 
    
    full_name.fget.short_description = "Ad Soyad"

    class Meta:
        verbose_name = "Yazar"
        verbose_name_plural = "Yazarlar"

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.title_tpyes[int(self.title_type)-1][1]})"
  
class File(models.Model):
    languages = (
        ('Türkçe','Türkçe'),
        ('İngilizce','İngilizce'),
        ('Fransızca','Fransızca'),
        ('Almanca','Almanca'),
        ('İtalyanca','İtalyanca'),
    )

    id = models.AutoField(primary_key=True)
    title = models.CharField("Dosya Başlığı", max_length=250,null=True, blank=True)
    description = models.TextField("Açıklama", null=True, blank=True)
    file_name = models.FileField("Dosya", upload_to="Drive",null=True, blank=True)
    file_cover = models.ImageField("Dosya Resmi", upload_to="Drive",null=True, blank=True)
    upload_date = models.DateTimeField(auto_now=True)
    date = models.DateField("Yüklenme Tarihi", null=True, blank=True)
    slug = models.SlugField(unique=True,db_index=True)
    language = models.CharField("Dil", max_length=100, choices=languages)
    outhor = models.ForeignKey(Outhor,on_delete=models.SET_NULL, null=True,blank=True)
    scholl = models.ForeignKey(Scholl, models.SET_NULL, null=True, blank=True)
    department = models.ForeignKey(Department, on_delete=models.SET_NULL, null=True, blank=True)
    lesson = models.ForeignKey(Lesson, on_delete=models.SET_NULL, null=True, blank=True)
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    is_active = models.BooleanField(default=0)
    is_home = models.BooleanField(default=0)

    class Meta:
        verbose_name = "Dosya"
        verbose_name_plural = "Dosyalar"

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = str(uuid.uuid4())[:8]

        super().save(*args, **kwargs)

class Slider(models.Model):
        id = models.AutoField(primary_key=True)
        title = models.CharField(max_length=200)
        image = models.ImageField(upload_to="files")
        file = models.ForeignKey(File, on_delete=models.SET_NULL, null=True, blank=True)
        is_active = models.BooleanField(default=False)

class Comment(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField("Kullanıcı Adı", max_length=30)
    email = models.EmailField("E-Posta", default="")
    text = models.TextField("Yorum", max_length=500)
    rating = models.IntegerField("Oy", null=True)
    date_added = models.DateTimeField("Yorum Tarihi", auto_now=True, null=True)
    file = models.ForeignKey(File, on_delete=models.CASCADE, related_name="comments")

    class Meta:
        verbose_name = "Yorum"
        verbose_name_plural = "Yorumlar"

DriveApp/Drive/views.py
from datetime import date
from django.shortcuts import render, get_object_or_404, redirect
from Drive.forms import CommentForm, FileUploadForm, FileEditForm, SchollForm, DepartmentForm, LessonForm, OuthorForm
from django.http.response import HttpResponseRedirect
from django.http import HttpResponse
from Drive.models import File, Slider, Scholl, Department, Lesson, Outhor
from Account.models import Profile
from django.urls import reverse
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required


@login_required(login_url='/Account/login')
def index(request):
    files = File.objects.filter(is_active=True, is_home=True) 
    sliders= Slider.objects.filter(is_active=True)
    return render(request, 'Drive/index.html',{
        "files": files,
        "sliders":sliders
    })

@login_required(login_url='/Account/login')
def files(request):
    files = File.objects.filter(is_active=True) 
    return render(request,'Drive/files.html',{
        "files": files
    })

@login_required(login_url='/Account/login')
def file_details(request, slug):

    file = get_object_or_404(File, slug=slug)
    comment_form = CommentForm()

    if request.method == "POST":
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.file = file
            comment.save()
            return HttpResponseRedirect(reverse("file_details", args=[slug]))

    return render(request,'Drive/file-details.html',{
        "file": file,
        "comments":file.comments.all().order_by("-date_added"),
        "comment_form": comment_form
    })

@login_required(login_url='/Account/login')
def file_upload(request):
    if request.method == 'POST':
        form = FileUploadForm(request.POST, request.FILES)
        if form.is_valid():
            file_instance = form.save(commit=False)
            file_instance.date = timezone.now()
            file_instance.user = request.user
            file_instance.save()
            messages.success(request,"Dosya Yüklendi")
            return redirect('file_upload')
        else:
            print(form.errors)
    else:
        form = FileUploadForm()


    return render(request, 'Drive/file-upload.html', {'form': form})

@login_required(login_url='/Account/login')
def download_file(request, file_slug):
    file_obj = get_object_or_404(File, slug=file_slug)
    file_data = file_obj.file_name.read()
    response = HttpResponse(file_data, content_type='application/octet-stream')
    response['Content-Disposition'] = f'attachment; filename="{file_obj.file_name.name}"'

    return response

@login_required(login_url='/Account/login')
def user_files(request):
    user_files = File.objects.filter(user=request.user)
    return render(request, 'Drive/user-files.html',{'user_files':user_files})

@login_required(login_url='/Account/login')
def edit_file(request, file_slug):
    file_instance = get_object_or_404(File, slug=file_slug)
    
    if request.method == 'POST':
        form = FileEditForm(request.POST, instance=file_instance)
        if form.is_valid():
            form.save()
            # Başarılı bir şekilde kaydedildiğinde yapılacak işlemler
    else:
        form = FileEditForm(instance=file_instance)
    
    return render(request, 'Drive/edit-file.html', {'form': form})

@login_required(login_url='/Account/login')
def add_school(request):
    if request.method == 'POST':
        form = SchollForm(request.POST)
        if form.is_valid():
            form.save()
            # Başarılı ekleme mesajı, başka bir sayfaya yönlendirme vs. burada yapılabilir.
    else:
        form = SchollForm()

    return render(request, 'Drive/addForms/add-school.html', {'form': form})

@login_required(login_url='/Account/login')
def scholl_list(request):
    scholls = Scholl.objects.all()
    return render(request, 'Drive/scholl-list.html', {'scholls': scholls})

@login_required(login_url='/Account/login')
def add_department(request):
    if request.method == 'POST':
        form = DepartmentForm(request.POST)
        if form.is_valid():
            form.save()
            # Başarılı ekleme mesajı, başka bir sayfaya yönlendirme vs. burada yapılabilir.
    else:
        form = DepartmentForm()

    return render(request, 'Drive/addForms/add-department.html', {'form': form})

def department_list(request):
    departments = Department.objects.all()
    return render(request, 'Drive/department-list.html', {'departments': departments})

@login_required(login_url='/Account/login')
def add_lesson(request):
    if request.method == 'POST':
        form = LessonForm(request.POST)
        if form.is_valid():
            form.save()
            # Başarılı ekleme mesajı, başka bir sayfaya yönlendirme vs. burada yapılabilir.
    else:
        form = LessonForm()
    return render(request, 'Drive/addForms/add-lesson.html', {'form': form})

@login_required(login_url='/Account/login')
def lesson_list(request):
    lessons = Lesson.objects.all()
    return render(request, 'Drive/lesson-list.html', {'lessons': lessons})

@login_required(login_url='/Account/login')
def add_outhor(request):
    if request.method=='POST':
        form = OuthorForm(request.POST)
        if form.is_valid():
            form.save()
    else:
        form = OuthorForm()
    return render(request, 'Drive/addForms/add-outhor.html',{'form':form})

@login_required(login_url='/Account/login')
def outhor_list(request):
    outhors = Outhor.objects.all()
    return render(request, 'Drive/outhor-list.html', {'outhors': outhors})

@login_required(login_url='/Account/login')
def profile_list(request):
    profiles = Profile.objects.all()
    return render(request, 'Drive/profile-list.html', {'profiles': profiles})

DriveApp/Drive/templates/partials/_add-comment.html
{% load static %} 
<h5 class="card-title mb-4">Bir Yorum Bırak</h5>
<form action="{% url 'file_details' file.slug  %}" method="POST" novalidate>
    {% csrf_token %}
    <div class="row">
        <div class="control-group form-group col-lg-4 col-md-4">
            <div class="controls">
                {{ comment_form.username.errors }}
                <label>{{ comment_form.username.label }}<span class="text-danger">*</span></label>
                {{ comment_form.username }}
            </div>
        </div>
        <div class="control-group form-group col-lg-4 col-md-4">
            <div class="controls">
                {{ comment_form.email.errors }}
                <label>{{ comment_form.email.label }}<span class="text-danger">*</span></label>
                {{ comment_form.email }}
            </div>
        </div>
        <div class="control-group form-group col-lg-4 col-md-4">
            <div class="controls">
                {{ comment_form.rating.errors }}
                <label>{{ comment_form.rating.label }} <span class="text-danger">*</span></label>
                {{ comment_form.rating }}
            </div>
        </div>
    </div>
    <div class="control-group form-group">
        <div class="controls">
            {{ comment_form.text.errors }}
            <label>{{ comment_form.text.label }} <span class="text-danger">*</span></label>
            {{ comment_form.text }}
        </div>
    </div>
    <div class="text-right">
        <button type="submit" class="btn btn-primary">Send Message</button>
    </div>
</form>

DriveApp/Drive/templates/partials/_add-menu.html
<div class="bg-white p-3 widget shadow rounded mb-4">
    <div class="nav nav-pills flex-column lavalamp" id="sidebar-1" role="tablist">
        <a class="nav-link" href="{% url "file_upload" %}" ><i class="fas fa-solid fa-paperclip fa-sm fa-fw mr-2 text-gray-400"></i> Dosya Yükle</a>
        <a class="nav-link" href="{% url "add_school" %}"><i class="fas fa-solid fa-school fa-sm fa-fw mr-2 text-gray-400"></i> Üniversite Ekle</a>
        <a class="nav-link" href="{% url "add_department" %}"><i class="fas fa-solid fa-graduation-cap fa-fw mr-2 text-gray-400"></i> Bölüm Ekle</a>
        <a class="nav-link" href="{% url "add_lesson" %}"><i class="fas fa-solid fa-graduation-cap fa-fw mr-2 text-gray-400"></i> Ders Ekle</a>
        <a class="nav-link" href="{% url "add_outhor" %}"><i class="fas fa-solid fa-pen-nib fa-fw mr-2 text-gray-400"></i> Yazar Ekle</a>
    </div>
</div>

DriveApp/Drive/templates/partials/_comment-list.html
{% load static %} 
{% load filters %}
{% for comment in comments  %}
                                                <div class="media mb-4">
                                                    <img class="d-flex mr-3 rounded-circle" src="{% static "img/s1.png" %}" alt="">
                                                    <div class="media-body">
                                                        <div class="mt-0 mb-1">
                                                            <span class="h6 mr-2 font-weight-bold text-gray-900">{{ comment.username }}</span> 
                                                            <span><i class="fa fa-calendar"></i> {{ comment.date_added }}</span>
                                                            <div class="stars-rating float-right">

                                                                {{comment.rating|display_rating|safe }}
                                                            </div>
                                                        </div>
                                                        <p>
                                                            {{ comment.text }}
                                                        </p>
                                                    </div>
                                                </div>                                          
                                            {% endfor %}

DriveApp/Drive/templates/partials/_file.html
{% load static %} 

<div class="card m-card shadow border-0">
    <a href="{% url "file_details" file.slug %}">
        <div class="m-card-cover">
            <!--<div class="position-absolute bg-white shadow-sm rounded text-center p-2 m-2 love-box">
                <h6 class="text-gray-900 mb-0 font-weight-bold"><i class="fas fa-heart text-danger"></i> 50%</h6>
                <small class="text-muted">8,784</small>
            </div>-->
            <img src="{{file.file_cover.url}}" class="card-img-top" alt="...">
        </div>
        <div class="card-body p-3">
            <h5 class="card-title text-gray-900 mb-1">
                {{file.title}}
            </h5>
            <p class="card-text">
                <small class="text-muted">
                    {{file.language|title}}
                </small> 
                <small class="text-danger">
                    <i class="fas fa-calendar-alt fa-sm text-gray-400"></i>
                    {{file.date}}
                </small>
            </p>
        </div>
    </a>
</div>

DriveApp/Drive/templates/partials/_footer.html
{% load static %} 

<footer class="sticky-footer bg-white">{% comment "" %}Footer Başlangıç{% endcomment %}
    <div class="container my-auto">
        <div class="copyright text-center my-auto">
            <span>
                Copyright © EduDrive 2023 | Made with
                <i class="fas fa-heart fa-fw text-danger"></i> by
                <a target="_blank" href="#">Bootstrap</a>
            </span>
        </div>
    </div>
</footer>{% comment "" %}Footer Bitiş{% endcomment %}

DriveApp/Drive/templates/partials/_sidebar.html
{% load static %} 

<ul class="navbar-nav sidebar sidebar-dark accordion" id="accordionSidebar">
    <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url "home_page" %}">
        <img src="{% static "Drive/img/BannerLogo.png" %}" alt="" />
    </a>

    <li class="nav-item active">
        <a class="nav-link" href="{% url "files_page" %}">
            <i class="fas fa-fw fa-film"></i>
            <span>Dosyalar</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="people.html">
            <i class="fas fa-fw fa-users"></i>
            <span>Dokümanlar</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "file_upload" %}">
            <i class="fas fa-fw fa-futbol"></i>
            <span>Dosya Yükle</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "ocr_document" %}">
            <i class="fas fa-fw fa-futbol"></i>
            <span>Doküman Tarat</span>
        </a>
    </li>
    <hr class="sidebar-divider" />

    <div class="sidebar-heading">Extra</div>
    <li class="nav-item">
        <a class="nav-link" href="{% url "scholl_list" %}">
            <i class="fas fa-fw fa-fire"></i>
            <span>Üniveriteler</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "department_list" %}">
            <i class="fas fa-fw fa-fire"></i>
            <span>Bölümler</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "lesson_list" %}">
            <i class="fas fa-fw fa-fire"></i>
            <span>Dersler</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "outhor_list" %}">
            <i class="fas fa-fw fa-fire"></i>
            <span>Yazarlar</span>
        </a>
    </li>
    <li class="nav-item">
        <a class="nav-link" href="{% url "404" %}">
            <i class="fas fa-fw fa-fire"></i>
            <span>Kullanıcılar</span>
        </a>
    </li>
</ul>

DriveApp/Drive/templates/partials/_slider.html
{% load static %} 

<div class="osahan-slider">
    {% for slide in sliders  %}
        <div class="osahan-slider-item">
            <a href="{% url "file_details" slide.file.slug %}" title={{ slide.title }}>
                <img src="{{slide.image.url}}" class="img-fluid rounded" alt="...">
            </a>          
        </div>   
    {% endfor %}
</div>

DriveApp/Drive/templates/partials/_spinner.html
{% load static %}
<div id="spinner" class="show bg-white position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center">
    <div class="spinner-border text-primary" style="width: 3rem; height: 3rem;" role="status">
        <span class="sr-only">Loading...</span>
    </div>
</div>

DriveApp/Drive/templates/partials/_topbar.html
{% load static %} 

<nav class="navbar navbar-expand navbar-dark topbar mb-4 pl-0 static-top shadow">
    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
        <i class="fa fa-bars"></i>
    </button>
    <form class="d-none d-sm-inline-block form-inline mr-auto my-2 my-md-0 mw-100 navbar-search">
        <div class="input-group">
            <input type="text" class="form-control bg-white border-0 small" placeholder="Arama yapmak istediğiniz dosyayı yazın..." aria-label="Search" aria-describedby="basic-addon2" />
            <div class="input-group-append">
                <button class="btn bg-white" type="button">
                    <i class="fas fa-search fa-sm"></i>
                </button>
            </div>
        </div>
    </form>
    <ul class="navbar-nav ml-auto">

        {% if user.is_authenticated  %}
                    
            <li class="nav-item dropdown no-arrow">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <span class="mr-2 d-none d-lg-inline text-gray-600 small">{{ user.username }}</span>
                    {% if user.profile.avatar %}
                        <img class="img-profile rounded-circle" src="{{ user.profile.avatar.url }}" />
                        {% else %}
                            <img class="img-profile rounded-circle" src="{% static "img\s1.png" %}" />
                    {% endif %}                  
                </a>

                <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="{% url "profile" %}">
                    <i class="fas fa-user-circle fa-sm fa-fw mr-2 text-gray-400"></i>
                    Profil
                </a>
                <a class="dropdown-item" href="{% url "liked_files" %}">
                    <i class="fas fa-heart fa-sm fa-fw mr-2 text-gray-400"></i>
                    Beğenilen Dosyalar
                </a>
                <a class="dropdown-item" href="{% url "change_password" %}">
                    <i class="fas fa-cog fa-sm fa-fw mr-2 text-gray-400"></i>
                    Şifre Değiştir
                </a>
                <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                        <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                        Çıkış Yap
                    </a>
                </div>
            </li>

            {% else %}
                <li class="nav-item">
                    <a href="{% url "login" %}" class="nav-link">Login</a>
                </li>
                <li class="nav-item">
                    <a href="{% url "register" %}" class="nav-link">Register</a>
                </li>
        {% endif %}
    </ul>
</nav>

DriveApp/Drive/templates/partials/_user-uploaded-files.html
{% load static %} 

<div class="card offer-card shadow border-0">
    <a href="{% url "file_details" file.slug %}">
       <div class="m-card-cover">
           {% if file.file_cover.url %}
              <img src="{{file.file_cover.url}}" class="card-img-top" alt="...">
           {% else %}
              <img src="{% static "Drive/img/o1.jpg" %}" class="card-img-top" alt="...">
           {% endif %}
       </div>
       <div class="card-body p-3">
            <p class="card-text text-gray-900 mt-3 mb-3">{{ file.title }}</p>
            <p class="card-text">
                <small class="text-muted"><span class="text-primary">{{ file.get_language_display }}</span></small>
                <small class="text-muted"><span class="text-gray-700">{{ file.upload_date }}</span></small>
            </p>
       </div>
    </a>
 </div>